version: '3'
services:
  glances-docker:
    build:
      context: .
      dockerfile: Dockerfile
    image: "glances-docker"
    container_name: "glances-docker-container"
    restart: unless-stopped
    pid: host
    network_mode: "host"
    environment:
      - TZ=Asia/Jakarta
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
